apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven-app-deployment
  namespace: apps
  labels:
    app: java-maven-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-maven-app-pod
  template:
    metadata:
      labels:
        app: java-maven-app-pod
    spec:
      containers:
        - name: java-maven-app
          image: apostoliseq/java-maven-app:1.0
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"